name:                01d
version:             0.1.0.0

dependencies:
- base == 4.14.3.0

ghc-options:
- -Wall

library:
  source-dirs:      src

tests:
  01d-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - 01d
    - hspec    
