name:                07d
version:             0.1.0.0

dependencies:
- base == 4.14.3.0
- containers == 0.6.5.1

ghc-options:
- -Wall

library:
  source-dirs:      src

tests:
  07d-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - 07d
    - hspec    
